version: '3.8'

services:
  oracle-db:
    image: gvenzl/oracle-xe:18.4.0-slim
    container_name: oracle-xe
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_PASSWORD=181005
    volumes:
      - oracle_data:/opt/oracle/oradata

  aspnet-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aspnet-app
    depends_on:
      - oracle-db
    environment:
      - ORACLE_CONNECTION_STRING=User Id=system;Password=181005;Data Source=oracle-db:1521/XEPDB1
    ports:
      - "5000:5000"

volumes:
  oracle_data:

